// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"learn/api/app"
	"learn/api/controllers"
	"learn/api/middlewares"
	"learn/api/repositories"
	"learn/api/services"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializeRouter() *http.Server {
	userRepositoryInterface := repositories.NewUserRepository()
	db := app.NewDb()
	validate := ProvideValidator()
	userServiceInterface := services.NewUserService(userRepositoryInterface, db, validate)
	userControllerInterface := controllers.NewUserController(userServiceInterface)
	router := app.NewRouter(userControllerInterface)
	authMiddleware := middlewares.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}
